stratagems=[
'airburst_rocket_launcher',
'anti-material_rifle',
'anti-personnel_minefield',
'arc_thrower',
'autocannon_sentry',
'autocannon',
'ballistic_shield_backpack',
'eagle_110mm_rocket_pods',
'eagle_500kg_bomb',
'eagle_airstrike',
'eagle_cluster_bomb',
'eagle_napalm_airstrike',
'eagle_rearm',
'eagle_smoke_strike',
'eagle_strafing_run',
'emancipator_exosuit',
'ems_mortar_sentry',
'expendable_anti-tank',
'flamethrower',
'gatling_sentry',
'grenade_launcher',
'guard_dog_rover',
'guard_dog',
'heavy_machine_gun',
'hellbomb',
'hmg_emplacement',
'incendiary_mines',
'jump_pack',
'laser_cannon',
'machine_gun_sentry',
'machine_gun',
'mortar_sentry',
'orbital_120mm_he_barrage',
'orbital_380mm_he_barrage',
'orbital_airburst_strike',
'orbital_ems_strike',
'orbital_gas_strike',
'orbital_gatling_barrage',
'orbital_illumination_flare',
'orbital_laser',
'orbital_precision_strike',
'orbital_railcannon_strike',
'orbital_smoke_strike',
'orbital_walking_barrage',
'patriot_exosuit',
'prospecting_drill',
'quasar_cannon',
'railgun',
'recoilless_rifle',
'reinforce',
'resupply',
'rocket_sentry',
'seaf_artillery',
'seismic_probe',
'shield_generation_relay',
'shield_generator_pack',
'sos_beacon',
'spear',
'sssd_delivery',
'stalwart',
'super_earth_flag',
'supply_pack',
'tesla_tower',
'upload_data',   
    
]

for stratagem in stratagems:
    batbody=f'''::@echo off
    "C:\\Users\jdwil\\anaconda3\\envs\\py3.11.4\\python.exe" "C:\\Python projects\\Git Dev\\Games\\helldivers_2_macros\\stratagem_macro.py" {stratagem} %*
    ::pause'''
    file= open(f'bats\\{stratagem}.bat','w')
    #bat body
    file.write(batbody)
    file.close